/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package spring.boot.examples;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.cache.annotation.EnableCaching;

@EnableCaching
@SpringBootApplication
public class SpringBootApplicationMain {
  public static void main(String[] args) {
    SpringApplication.run(SpringBootApplicationMain.class, args);
  }
}
